import dynamic from 'next/dynamic'

// Feather Icons (FI)
export const FiSend = dynamic(() => import('react-icons/fi').then(mod => mod.FiSend))
export const FiPlus = dynamic(() => import('react-icons/fi').then(mod => mod.FiPlus))
export const FiImage = dynamic(() => import('react-icons/fi').then(mod => mod.FiImage))
export const FiSmile = dynamic(() => import('react-icons/fi').then(mod => mod.FiSmile))
export const FiPaperclip = dynamic(() => import('react-icons/fi').then(mod => mod.FiPaperclip))
export const FiGift = dynamic(() => import('react-icons/fi').then(mod => mod.FiGift))
export const FiUser = dynamic(() => import('react-icons/fi').then(mod => mod.FiUser))
export const FiLogOut = dynamic(() => import('react-icons/fi').then(mod => mod.FiLogOut))
export const FiVideo = dynamic(() => import('react-icons/fi').then(mod => mod.FiVideo))
export const FiSun = dynamic(() => import('react-icons/fi').then(mod => mod.FiSun))
export const FiMoon = dynamic(() => import('react-icons/fi').then(mod => mod.FiMoon))
export const FiX = dynamic(() => import('react-icons/fi').then(mod => mod.FiX))
export const FiMessageSquare = dynamic(() => import('react-icons/fi').then(mod => mod.FiMessageSquare))
export const FiYoutube = dynamic(() => import('react-icons/fi').then(mod => mod.FiYoutube))
export const FiMoreVertical = dynamic(() => import('react-icons/fi').then(mod => mod.FiMoreVertical))
export const FiCopy = dynamic(() => import('react-icons/fi').then(mod => mod.FiCopy))
export const FiCheck = dynamic(() => import('react-icons/fi').then(mod => mod.FiCheck))
export const FiChevronDown = dynamic(() => import('react-icons/fi').then(mod => mod.FiChevronDown))
export const FiPlay = dynamic(() => import('react-icons/fi').then(mod => mod.FiPlay))
export const FiPause = dynamic(() => import('react-icons/fi').then(mod => mod.FiPause))
export const FiLink = dynamic(() => import('react-icons/fi').then(mod => mod.FiLink))
export const FiArrowLeft = dynamic(() => import('react-icons/fi').then(mod => mod.FiArrowLeft))

// Bootstrap Icons (BS)
export const BsChatDots = dynamic(() => import('react-icons/bs').then(mod => mod.BsChatDots))
export const BsYoutube = dynamic(() => import('react-icons/bs').then(mod => mod.BsYoutube))
export const BsPeople = dynamic(() => import('react-icons/bs').then(mod => mod.BsPeople))

// Font Awesome Icons (FA)
export const FaCrown = dynamic(() => import('react-icons/fa').then(mod => mod.FaCrown)) 