services:
  - type: web
    name: umeet
    env: node
    region: singapore
    plan: free
    buildCommand: |
      rm -rf node_modules
      rm -rf .next
      rm -rf dist
      npm cache clean --force
      npm install
      npm install postcss-nesting@12.0.2
      npm run build
      ls -la dist/
    startCommand: NODE_ENV=production node --experimental-specifier-resolution=node --experimental-modules dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXT_FONT_OPTIMIZE
        value: "true"
      - key: NODE_VERSION
        value: "20.x"
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: umeet-socket
    env: node
    plan: standard
    buildCommand: |
      rm -rf node_modules
      rm -rf dist
      npm cache clean --force
      npm install
      npm install postcss-nesting@12.0.2
      tsc -p tsconfig.server.json
      cp -r models dist/
      cp -r app/lib dist/app/
      ls -la dist/
    startCommand: NODE_ENV=production node --experimental-specifier-resolution=node --experimental-modules dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://umeet.onrender.com
      - key: NEXTAUTH_URL
        value: https://umeet.onrender.com
      - key: CORS_ORIGIN
        value: https://umeet.onrender.com
      - key: NODE_VERSION
        value: "20.x"
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - umeet-socket.onrender.com 