services:
  - type: web
    name: umeet
    env: node
    region: singapore
    plan: free
    buildCommand: |
      rm -rf node_modules
      rm -rf .next
      npm cache clean --force
      npm install
      npm install postcss-nesting@12.0.2
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXT_FONT_OPTIMIZE
        value: "true"
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: umeet-socket
    env: node
    plan: standard
    buildCommand: |
      rm -rf node_modules
      npm cache clean --force
      npm install
      npm install postcss-nesting@12.0.2
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://umeet.onrender.com
      - key: NEXTAUTH_URL
        value: https://umeet.onrender.com
      - key: CORS_ORIGIN
        value: https://umeet.onrender.com
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - umeet-socket.onrender.com 